### PR TITLE
Add new script for rpmlint.

### PR DESCRIPTION
**Pull request by marxin**
The script is used to generate licenses.toml configuration
file consumed by rpmlint.

### CODE REVIEW

**Comment by scarabeusiv** [comment]
Makefile should generate the file like the licenses list then.

Also why don't you use fstrings f'{variable}'?

**Comment by marxin** [comment]
> Makefile should generate the file like the licenses list then.

Added.

> 
> Also why don't you use fstrings f'{variable}'?

I'm not familiar with that, but I'll learn it. I promise!
And I changed that in the pull request.

**Comment by scarabeusiv** [comment]
You don't have to gitignore the file i would say, we can keep it in the scm and regenerate it on releases. Then you can fetch it from releases/git here and not rely on it anywhere else?

**Comment by scarabeusiv** [comment]
All the conversion tables afterall are generated and we keep them stored.

**Comment by scarabeusiv** [comment]
Also what the ... is again with coveralls, i start to hate that package, every 3 months different approach on how to add the stuff...

**Comment by marxin** [comment]
> All the conversion tables afterall are generated and we keep them stored.

Done that.

**Comment by marxin** [comment]
I also removed the strange `First line` from `data/licenses_changes.txt` file.

**Pull request merged**
